hash-format = "sha256"

[[files]]
file = "config/betterf3.json"
hash = "0028abb010568e5d31c2d12390a18a471a495591a24bf408abea3c151e8d234e"

[[files]]
file = "config/fastquit.toml"
hash = "de22af584433dfdfb4a14b85091bfbd5c6be697a306499c2d7c75740658dbad4"

[[files]]
file = "config/iris.properties"
hash = "8fb805ba7d12cca2b39786acecd4a52c7b33e7eb1ccd906af1562cb465c8c737"

[[files]]
file = "config/nomorepopups.json"
hash = "e786365dc27656ea69e2f990eb932d256a3950894e886b012259fa92e8f6e764"

[[files]]
file = "config/roughlyenoughitems/config.json5"
hash = "6160c0e00f3391cd34fafcb2ea6c66e00a0e43a8d25d401077e974a397b54326"

[[files]]
file = "mods/animatica.pw.toml"
hash = "e94fd2f80b6029f19fb0c68d5bbf443a21645af0d668c5a544e3b3f23508fb61"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e12dce3e543168379a2856c66064ee2001e6420a9dfc6163f37b78e518947456"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "7a266a082b54627e5f95aa154871114fded8c0a06af104e49cf08668b869cfad"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "a1e024094c28068c99a6da1c5867cbd4e66a315718039659bfa533a138762d9e"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "ec2c437fe50a3f8ea6077215974ba9f769cb94eb29432156cbbe43137a74013f"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "d2e1ad62031e3700de73a87957a4acca747436a4135da695705cb5d293aa0890"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "5944ed5a779d142aea9ccd8c466a20fa3d9233a29f2be1e5ae54fc15f5edd57e"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "ce0b6c452313b669ce95d6bc7f232f72b89bf61ebb2013cac5b17a09c8132510"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "c9102ad224c1496927d326707ee2cd2a2cfd6f278f05e23a19aa45395306daf6"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "b13f84a7fad7d6e21cef513a9c8f8206e55f0b342b4030df540e3126ad5abb2a"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "58a487d9e3761d18f529cf141c873ea054e8f26c5e90601a3c8cf60fc723b22d"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "605c081279d8e4e5c98e6a50304867214185d8b8f14434b71d388a20f4ad7d5d"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "c9c33bb929d2133e53cd332660d964d2d417396039affddbaf057fb7a9d5b36d"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/hot-reload-resource-packs.pw.toml"
hash = "6337b1d8e1e45bb0cd1bfdde207e9b7c3fe87f53155bfba168d93781041f54c4"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "060c6baaec85f47ba4bc2c0f4b8642b9933c27d3c166eb00ef86b4bbfd7f34a3"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "00c3654d5fdf572400f15ef8dd115e9b68ded2e6289e93fb42dba52333998dcd"
metafile = true

[[files]]
file = "mods/invmovecompats.pw.toml"
hash = "8a8dd75f4e258a1cfb83c49e7d2b2530f93c7aaa9deb28fd38bb511eeeca0d9f"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c8695e51366b601c5e9118a5d5650d234cc25fc8d1f90ebd186c17c199ba7fca"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "4b1b29ebfbbd9f23eb90c8c9f5113fce64c3ca605c8cad3aedaa25be83a82a53"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "f43c82e3cc6079291ddae81445c703905b6c670dd43f444e47f5cd817944e822"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "dbb344ad3e49c36d167fa05b6c5f674794306b1727220e8720d767264aee497f"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "b6685e98fce8f1f45868b9df3dbaa410ec23bb64896c826be596d98b01326116"
metafile = true

[[files]]
file = "mods/no-more-popups.pw.toml"
hash = "16ca9779ae1e66ad2468bbc94ca64107544e1c70210c4ae07980ac4ffbd67e4f"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
hash = "421b6b05164e623dc65e0e4133fc484fb3b87b26b040ad4b2ffb239491d8bb2d"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "9ed765da71f977af16c71b3ff56356dea5a149d9626277e4d4868941f8efa1b0"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "4384bc790b955c7329be45a0f5a140f7159598718076e8c06d425f91cefbba87"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "80d9a8c3e6322d92adfe29f68bceff1ac16aae8f95cb60bf8206a0ec94e056af"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "2c5d9c47c2c16b1207f1335d10f99b1ba976bdc3363784674b8907ddd96e9c0a"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "83164a6af3923e28cadf9d404f059bf74aa4f0842fc1ca0f6e7cf1e686044875"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8305bf17272f0c579b0930b751c12089de9fb157dbdb5c080836ce3daad310b5"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "d2d5a9c835661b4f6f718fd057f03594b87aa49d1bcd9711af8553e51ea4a6fb"
metafile = true

[[files]]
file = "options.txt"
hash = "242dbfe356b6217f54478aa5d8e366010d72a41d6a735256f81b4f673d76e354"
