name = "Resource Pack Maker"
author = "Alfakynz"
version = "1.0.0-b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4a0c665c1d8c7ff304ccdcb1ed313ef04b5d4c31a7be210e30f3e0130d0c711"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
