hash-format = "sha256"

[[files]]
file = "config/betterf3.json"
hash = "0028abb010568e5d31c2d12390a18a471a495591a24bf408abea3c151e8d234e"

[[files]]
file = "config/fastquit.toml"
hash = "de22af584433dfdfb4a14b85091bfbd5c6be697a306499c2d7c75740658dbad4"

[[files]]
file = "config/iris.properties"
hash = "8fb805ba7d12cca2b39786acecd4a52c7b33e7eb1ccd906af1562cb465c8c737"

[[files]]
file = "config/nomorepopups.json"
hash = "e786365dc27656ea69e2f990eb932d256a3950894e886b012259fa92e8f6e764"

[[files]]
file = "config/roughlyenoughitems/config.json5"
hash = "6160c0e00f3391cd34fafcb2ea6c66e00a0e43a8d25d401077e974a397b54326"

[[files]]
file = "icon.png"
hash = "c6ddd19bac8165eb2f1eaf2a3d7c94b9fec46c9e40cf29c4b2157174405afb3e"

[[files]]
file = "mods/animatica.pw.toml"
hash = "ff31791271197f8122fb52893e7e67d86ba038dd0e77e57227ef84de8f7e069e"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "39f761298d831e49308b1507c2ac1e524f4ad07f220621e45290c810deb1c497"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "7d1815ec4f2098c4de8b01494373d84da8a5104accd5ae028a2a020595646082"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "c899acdc322ab52800a6e305a16427297f411c1c39d97983be96e8b6a34e157c"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "6d511d91e17e09d36b0b0c7065b07eb604146bc9f3df0fbc932948aaf33aa440"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "7797b4dcd9c68b4555caf2629b0bff76f234ae04e8b42956e95ce2c65807049e"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "4effaea1cdc0ccd0de4a94ab435cc3cb22085933fca7e1dd35b9fb8953a1ce9e"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "b1f89407254a20cde6c60994a6315bd841b7f562669a1d29b436ec97463ff2ae"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "4898b9beb1b7cf7df38346b02d9756c10e09408b6344e3295fe7177b25549f14"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "054628ed76bd95bde1dbb4343721f3fbed87c8ad798ce99fc74b1171c39b6400"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "1824d1cc8f4f82a88972b9220dc6806c05968d651fb38f6bfe69e4d8215fc0ed"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "4387abb74dcfc93f9381c109fe76e7161ca7a91a1a642db4781b47f650c4ddab"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/hot-reload-resource-packs.pw.toml"
hash = "6337b1d8e1e45bb0cd1bfdde207e9b7c3fe87f53155bfba168d93781041f54c4"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "907ed71a8d572d5bc2a8f956b0b0d0fad37e1d5bdd48464041a76ef8fca79cb7"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "fff3bd7b56f7f5866bacf83173ceb9d24c0a2684e4de6f8cb4d7f0173ff78455"
metafile = true

[[files]]
file = "mods/invmovecompats.pw.toml"
hash = "6a1fd74a1307161a86e40af4a68ebb5c2b3a04036d688c6a1021f70671f492ef"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5284f6d141a990f4ea021c12b851e07102f5cb22743cf7b33be6ad2eb4c8d3f5"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "80858e1b1477432110b72aab33348635139d6e8fe7bc05db3ba00651de635720"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "10d2cb5f575d0c290549758cafe0e3b15acbca8c5163aa4209cbe4fb8fcb7de5"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5564dbbe8adc0ba450afc6a1c3eef82f183a53ede5f3b1de0bc6ca320aadc5e9"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "44b266511a87dd03b2160cf7aa117d239e1acaa3450eb1707359192b59025705"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "b9651d06e56ad51c1cdcf4b03b6a34328b7dc941f263ff92b189ee26a47cc224"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "6be43ffc708ac329843aee99ededc692ecf6461ee8e409d373f55fc5494db5af"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "7fc969e77edc3b0b9946b42070fd858349a74555f0cf9648907241af8a3a2d25"
metafile = true

[[files]]
file = "mods/no-more-popups.pw.toml"
hash = "16ca9779ae1e66ad2468bbc94ca64107544e1c70210c4ae07980ac4ffbd67e4f"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
hash = "0846c709603ff778d27f6afe12caa9fedf0648b7d7182a969fd08fe6432b5cc9"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "6f45c3f2ec9005b18846088784d291f4dabcce7b569031fb44855845a33aa8f7"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "2e2c1b47b513663871e71c89a699c66ac9fcc97633f007ed064ce4410f220f5a"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "271640453d095244948889863c5f8497fedc69b8604055213a295061af5c09c1"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "802f3efc129ab62029ac7dc9f24c5e947745346d2ce972442994d83031cdc26c"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "d22546ad55b555931eb527f163b3564e00c12c7dc8101378b87447dfcc8e0652"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "6891f1e1b0b0fd3650023b8e984447f7e0a3e1488a203fec0cdfd201a9a59ee7"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "59943cbd2c0e4e90f65002e17704bca571acb09b095fc69fdf430df4bfd42870"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8ffa4ba1466882a5abef6c6d220824f1ce4e228771f854f19e4fceb80598723c"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "fb09f6357ae2e3dcfea36520efde6e9b761efffc63b4dfdec5e4b11011bac58c"
metafile = true

[[files]]
file = "options.txt"
hash = "242dbfe356b6217f54478aa5d8e366010d72a41d6a735256f81b4f673d76e354"
