name = "Resource Pack Maker"
author = "Alfakynz"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dab592ff6d8f88e105e2380bcfc507ef061484f544e6382cadb2af2b69f6bd72"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
